### ISSUE TITLE
'ESC' characters in build output

### ISSUE THREAD

**Issue by latenitecali** [snowkit/sublime_flow#11]
![screenshot 2016-03-27 23 36 10](https://cloud.githubusercontent.com/assets/1631578/14072386/bace3960-f474-11e5-9a4f-17b1417808d1.png)
I don't know if this is just a theme setting, but some light googling leads me to believe this is ANSI character encoding in the build output not being displayed correctly. Is there a way to fix this on the flow side, or is this something Sublime or a plugin can fix?

**Comment by ruby0x1** [comment]
This comes from hxcpp, [it's supposed to detect when color is supported](https://github.com/HaxeFoundation/hxcpp/blob/6ee411325db0a15051075f5dc12c0787d4c55e00/tools/hxcpp/Log.hx#L122), and not emit it when it's not.

I don't have these in my sublime on any of my mac/windows/linux machines, even from fresh installs, so I'm not entirely sure where yours are coming from. `flow`, `sublime_flow` and `sublime_haxe` don't mention color at all, so it's not configured by the build workflow. 

Also when I run in terminal I get the colors, in sublime I don't.

You can set the [HXCPP_NO_COLOUR](https://github.com/HaxeFoundation/hxcpp/blob/8101cfe55d502f1c50f13b0c63531331db6810c9/tools/hxcpp/BuildTool.hx#L963) define (or pass `-nocolor` in the hxcpp flags) to force it off, but it is strange that it's enabled from sublime somehow.

**Comment by latenitecali** [comment]
The weird part is that sometimes I see these ESC characters, sometimes I don't. I'm pretty sure when I don't, there's no colors, but it's so infrequent it's hard to say. I do see some color when building in Terminal, but it's not really important to me, so I'll try out the no color options.

**Comment by ruby0x1** [comment]
You can set it using `flow config` as a user-specific default for all flow projects if you don't want to lug it around to every .flow file you use.

**Comment by latenitecali** [comment]
If I set -nocolor in the build/flags node, it says error: unknown option

**Comment by ruby0x1** [comment]
It's `project.build.hxcpp.flags` if talking to hxcpp directly. The other is haxe flags.

**Comment by latenitecali** [comment]
ah, yes that works great! Now trying to figure out the flow config so this can just be a default.

actually, I can just add this flag to my default project folder. Thanks for the help!
